version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    links:
     - mongo-database
  mongo-database :
    image: mongo
    volumes:  
     - /data/db:/data/db
    ports:
     - "27017:27017"